// src/app/layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import { gabarito } from './fonts'
import AppLayout from '@/components/appLayout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`antialiased bg-[#f0f4f5] ${gabarito.variable} `}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  )
}
